// generated by stringer -type=ZookeeperError; DO NOT EDIT

package gozoo

import "fmt"

const _ZookeeperError_name = "ZooOkZooSystemErrorZooRuntimeInconsistencyErrorZooDataInconsistencyErrorZooConnectionLossErrorZooMarshallingErrorZooUnimplementedErrorZooOperationTimeoutErrorZooBadArgumentsErrorZooInvalidStateErrorZooApiErrorZooNoNodeErrorZooNoAuthErrorZooBadVersionErrorZooNoChildrenForEphemeralsErrorZooNodeExistsErrorZooNotEmptyErrorZooSessionExpiredErrorZooInvalidCallbackErrorZooInvalidAclErrorZooAuthFailedErrorZooClosingErrorZooNothingErrorZooSessionMovedErrorZooUnknownError"

var _ZookeeperError_index = [...]uint16{0, 5, 19, 47, 72, 94, 113, 134, 158, 178, 198, 209, 223, 237, 255, 286, 304, 320, 342, 365, 383, 401, 416, 431, 451, 466}

func (i ZookeeperError) String() string {
	if i < 0 || i+1 >= ZookeeperError(len(_ZookeeperError_index)) {
		return fmt.Sprintf("ZookeeperError(%d)", i)
	}
	return _ZookeeperError_name[_ZookeeperError_index[i]:_ZookeeperError_index[i+1]]
}
