// generated by stringer -type=ZookeeperEvent; DO NOT EDIT

package gozoo

import "fmt"

const _ZookeeperEvent_name = "ZooCreatedEventZooDeletedEventZooChangedEventZooChildEventZooSessionEventZooNotWatchingEventZooUnknownEvent"

var _ZookeeperEvent_index = [...]uint8{0, 15, 30, 45, 58, 73, 92, 107}

func (i ZookeeperEvent) String() string {
	if i < 0 || i+1 >= ZookeeperEvent(len(_ZookeeperEvent_index)) {
		return fmt.Sprintf("ZookeeperEvent(%d)", i)
	}
	return _ZookeeperEvent_name[_ZookeeperEvent_index[i]:_ZookeeperEvent_index[i+1]]
}
